services:
  - type: web
    name: calendar-backend
    runtime: node
    rootDir: back
    buildCommand: yarn install && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: FRONT_END_URL
        sync: false
